### PR TITLE
Detect reference frame based on date and simplify math

### PR DESCRIPTION
**Pull request by tengkunuddin**
Detect reference frame based on date. All GNSS processing post 27.11.2023 are assigned with ITRF2020 reference frame tag, while data pre-27.11.2023 are ITRF2014. Reference frame corresponds to the IGS precise orbit's reference frame .

Sigma a posteriori math simplified.

### CODE REVIEW

**Review by harry093 — COMMENTED** [review]
Thanks @tengkunuddin! I am happy with the simplified maths but could you explain to me the automatic assigning of the reference frame. I'll admit that I've never worked with Leica Infinity so can't really comment, but it seems to me that someone could still have the reference frame set to ITRF2014 after that date. Is that not  possible?

**Comment by wapayze** [comment]
@harry093 The exported .asc file shows the epoch for the baseline as DD.MM.YYY hh:mm:ss. If I'm reading the script correctly, it reads the date and then assigns the reference frame based on whether it is from 27.11.2022 and assigns ITRF2020 the reference frame. Within Infinity the thing to look for is which .atx file you are using as they are how you go from GNSS measurment to IGS frame to refence frame. Is that right @tengkunuddin?

**Comment by tengkunuddin** [comment]
@wapayze @harry093 my apologies for the late response! That is correct, the datum is assigned based on the GNSS survey dates. We were technically 'forced' to change to ITRF2020 as IGS stopped providing ITRF2014 GNSS products (i.e. orbits, clocks, orbits) from the end of November 2022. So based on this logic, any processed data from this date are in ITRF2020. In an ideal processing workflow, we should be using the newer IGS20 antenna calibration files as well. 

You raised an interesting point though, as we could technically reprocess GNSS data before Nov 2022 using the Repro3 products and get ITRF2020 coordinates. However, the output file is pretty simple - we could just do a find and replace operation in a text editor to assign the desired reference frame.

**Comment by harry093** [comment]
Thanks for the explanation @tengkunuddin and @wapayze!

**Pull request merged**
