### PR TITLE
In DynaShp_adj.py: add description field from adj, add to stn.shp

### PR DESCRIPTION
**Pull request by BatchelorJ**
Reads description field from adj file for each station, adds this as a field to the station shapefile.

### CODE REVIEW

**Comment by nicgowans** [comment]
Great idea, Josh. But I think we could make the description read a little more robust. As is, this strategy will run into trouble if stn-corrections are turned (appearing between standard deviations and Description fields), or if the station description contains either spaces or commas.

I'd suggest the following strategy: 
1. detect the adjusted coordinates header line and find the Description index.
2. use this index to read in the description. It might look something like:

```
    if stn_line:
        if line_count == stn_line - 2:
            if 'Description' in line:
                desc_index = line.find('Description')

    ...

    Desc = line[desc_index:].strip()

```
Cheers,
Nic

**Comment by harry093** [comment]
@BatchelorJ @nicgowans agreed. Good idea. As Nic wrote this code I will leave it for you two to iterate on. If you need me to merge let me know when you are both happy with the changes

**Comment by BatchelorJ** [comment]
Thanks for the great feedback @nicgowans !

I've modified the description finder to look for the index of the Description in the station list header and added some basic silent error handling (I don't think Description can be turned off in the adj output, but if it's missing then the description field for each station in the shapefile will be Null).

Let me know what you think.

Cheers,
Josh

**Comment by nicgowans** [comment]
Awesome work @BatchelorJ. Looks good to go.

Nic

**Pull request merged**
